//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIEvidenceRecord) DeepCopyInto(out *AIEvidenceRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIEvidenceRecord.
func (in *AIEvidenceRecord) DeepCopy() *AIEvidenceRecord {
	if in == nil {
		return nil
	}
	out := new(AIEvidenceRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIEvidenceRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIEvidenceRecordList) DeepCopyInto(out *AIEvidenceRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIEvidenceRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIEvidenceRecordList.
func (in *AIEvidenceRecordList) DeepCopy() *AIEvidenceRecordList {
	if in == nil {
		return nil
	}
	out := new(AIEvidenceRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIEvidenceRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIEvidenceRecordSpec) DeepCopyInto(out *AIEvidenceRecordSpec) {
	*out = *in
	out.SubjectRef = in.SubjectRef
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIEvidenceRecordSpec.
func (in *AIEvidenceRecordSpec) DeepCopy() *AIEvidenceRecordSpec {
	if in == nil {
		return nil
	}
	out := new(AIEvidenceRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIEvidenceRecordStatus) DeepCopyInto(out *AIEvidenceRecordStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIEvidenceRecordStatus.
func (in *AIEvidenceRecordStatus) DeepCopy() *AIEvidenceRecordStatus {
	if in == nil {
		return nil
	}
	out := new(AIEvidenceRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIKeyReleasePolicy) DeepCopyInto(out *AIKeyReleasePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIKeyReleasePolicy.
func (in *AIKeyReleasePolicy) DeepCopy() *AIKeyReleasePolicy {
	if in == nil {
		return nil
	}
	out := new(AIKeyReleasePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIKeyReleasePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIKeyReleasePolicyList) DeepCopyInto(out *AIKeyReleasePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIKeyReleasePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIKeyReleasePolicyList.
func (in *AIKeyReleasePolicyList) DeepCopy() *AIKeyReleasePolicyList {
	if in == nil {
		return nil
	}
	out := new(AIKeyReleasePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIKeyReleasePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIKeyReleasePolicySpec) DeepCopyInto(out *AIKeyReleasePolicySpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.EvidenceRef != nil {
		in, out := &in.EvidenceRef, &out.EvidenceRef
		*out = new(ObjectReference)
		**out = **in
	}
	out.KeyRelease = in.KeyRelease
	if in.AllowedSecrets != nil {
		in, out := &in.AllowedSecrets, &out.AllowedSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	out.Audit = in.Audit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIKeyReleasePolicySpec.
func (in *AIKeyReleasePolicySpec) DeepCopy() *AIKeyReleasePolicySpec {
	if in == nil {
		return nil
	}
	out := new(AIKeyReleasePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIKeyReleasePolicyStatus) DeepCopyInto(out *AIKeyReleasePolicyStatus) {
	*out = *in
	if in.LastDecisionTime != nil {
		in, out := &in.LastDecisionTime, &out.LastDecisionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIKeyReleasePolicyStatus.
func (in *AIKeyReleasePolicyStatus) DeepCopy() *AIKeyReleasePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AIKeyReleasePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPlacementDecision) DeepCopyInto(out *AIPlacementDecision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPlacementDecision.
func (in *AIPlacementDecision) DeepCopy() *AIPlacementDecision {
	if in == nil {
		return nil
	}
	out := new(AIPlacementDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIPlacementDecision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPlacementDecisionList) DeepCopyInto(out *AIPlacementDecisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIPlacementDecision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPlacementDecisionList.
func (in *AIPlacementDecisionList) DeepCopy() *AIPlacementDecisionList {
	if in == nil {
		return nil
	}
	out := new(AIPlacementDecisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIPlacementDecisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPlacementDecisionSpec) DeepCopyInto(out *AIPlacementDecisionSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.PolicyRef = in.PolicyRef
	if in.EvidenceRef != nil {
		in, out := &in.EvidenceRef, &out.EvidenceRef
		*out = new(ObjectReference)
		**out = **in
	}
	out.PlacementToken = in.PlacementToken
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPlacementDecisionSpec.
func (in *AIPlacementDecisionSpec) DeepCopy() *AIPlacementDecisionSpec {
	if in == nil {
		return nil
	}
	out := new(AIPlacementDecisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPlacementDecisionStatus) DeepCopyInto(out *AIPlacementDecisionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPlacementDecisionStatus.
func (in *AIPlacementDecisionStatus) DeepCopy() *AIPlacementDecisionStatus {
	if in == nil {
		return nil
	}
	out := new(AIPlacementDecisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIRevocationPolicy) DeepCopyInto(out *AIRevocationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIRevocationPolicy.
func (in *AIRevocationPolicy) DeepCopy() *AIRevocationPolicy {
	if in == nil {
		return nil
	}
	out := new(AIRevocationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIRevocationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIRevocationPolicyList) DeepCopyInto(out *AIRevocationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIRevocationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIRevocationPolicyList.
func (in *AIRevocationPolicyList) DeepCopy() *AIRevocationPolicyList {
	if in == nil {
		return nil
	}
	out := new(AIRevocationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIRevocationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIRevocationPolicySpec) DeepCopyInto(out *AIRevocationPolicySpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.EvidenceRef != nil {
		in, out := &in.EvidenceRef, &out.EvidenceRef
		*out = new(ObjectReference)
		**out = **in
	}
	if in.PlacementRef != nil {
		in, out := &in.PlacementRef, &out.PlacementRef
		*out = new(ObjectReference)
		**out = **in
	}
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Audit = in.Audit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIRevocationPolicySpec.
func (in *AIRevocationPolicySpec) DeepCopy() *AIRevocationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AIRevocationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIRevocationPolicyStatus) DeepCopyInto(out *AIRevocationPolicyStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIRevocationPolicyStatus.
func (in *AIRevocationPolicyStatus) DeepCopy() *AIRevocationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AIRevocationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttestationEvidence) DeepCopyInto(out *AttestationEvidence) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttestationEvidence.
func (in *AttestationEvidence) DeepCopy() *AttestationEvidence {
	if in == nil {
		return nil
	}
	out := new(AttestationEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttestationEvidence) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttestationEvidenceList) DeepCopyInto(out *AttestationEvidenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AttestationEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttestationEvidenceList.
func (in *AttestationEvidenceList) DeepCopy() *AttestationEvidenceList {
	if in == nil {
		return nil
	}
	out := new(AttestationEvidenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttestationEvidenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttestationEvidenceSpec) DeepCopyInto(out *AttestationEvidenceSpec) {
	*out = *in
	out.SubjectRef = in.SubjectRef
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(ObjectReference)
		**out = **in
	}
	out.Runtime = in.Runtime
	out.Freshness = in.Freshness
	if in.Signatures != nil {
		in, out := &in.Signatures, &out.Signatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttestationEvidenceSpec.
func (in *AttestationEvidenceSpec) DeepCopy() *AttestationEvidenceSpec {
	if in == nil {
		return nil
	}
	out := new(AttestationEvidenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttestationEvidenceStatus) DeepCopyInto(out *AttestationEvidenceStatus) {
	*out = *in
	if in.LastVerifiedTime != nil {
		in, out := &in.LastVerifiedTime, &out.LastVerifiedTime
		*out = (*in).DeepCopy()
	}
	if in.IssuedAt != nil {
		in, out := &in.IssuedAt, &out.IssuedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttestationEvidenceStatus.
func (in *AttestationEvidenceStatus) DeepCopy() *AttestationEvidenceStatus {
	if in == nil {
		return nil
	}
	out := new(AttestationEvidenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialGPURequirements) DeepCopyInto(out *ConfidentialGPURequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialGPURequirements.
func (in *ConfidentialGPURequirements) DeepCopy() *ConfidentialGPURequirements {
	if in == nil {
		return nil
	}
	out := new(ConfidentialGPURequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialInferencePolicy) DeepCopyInto(out *ConfidentialInferencePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialInferencePolicy.
func (in *ConfidentialInferencePolicy) DeepCopy() *ConfidentialInferencePolicy {
	if in == nil {
		return nil
	}
	out := new(ConfidentialInferencePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfidentialInferencePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialInferencePolicyList) DeepCopyInto(out *ConfidentialInferencePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfidentialInferencePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialInferencePolicyList.
func (in *ConfidentialInferencePolicyList) DeepCopy() *ConfidentialInferencePolicyList {
	if in == nil {
		return nil
	}
	out := new(ConfidentialInferencePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfidentialInferencePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialInferencePolicySpec) DeepCopyInto(out *ConfidentialInferencePolicySpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.RequiredTEE != nil {
		in, out := &in.RequiredTEE, &out.RequiredTEE
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(ConfidentialGPURequirements)
		**out = **in
	}
	if in.AllowedRuntimeClasses != nil {
		in, out := &in.AllowedRuntimeClasses, &out.AllowedRuntimeClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.KeyRelease = in.KeyRelease
	out.Audit = in.Audit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialInferencePolicySpec.
func (in *ConfidentialInferencePolicySpec) DeepCopy() *ConfidentialInferencePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ConfidentialInferencePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialInferencePolicyStatus) DeepCopyInto(out *ConfidentialInferencePolicyStatus) {
	*out = *in
	if in.EffectiveRuntime != nil {
		in, out := &in.EffectiveRuntime, &out.EffectiveRuntime
		*out = new(RuntimeExpectation)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialInferencePolicyStatus.
func (in *ConfidentialInferencePolicyStatus) DeepCopy() *ConfidentialInferencePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ConfidentialInferencePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceFreshness) DeepCopyInto(out *EvidenceFreshness) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceFreshness.
func (in *EvidenceFreshness) DeepCopy() *EvidenceFreshness {
	if in == nil {
		return nil
	}
	out := new(EvidenceFreshness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementTokenSpec) DeepCopyInto(out *PlacementTokenSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementTokenSpec.
func (in *PlacementTokenSpec) DeepCopy() *PlacementTokenSpec {
	if in == nil {
		return nil
	}
	out := new(PlacementTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAuditSpec) DeepCopyInto(out *PolicyAuditSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAuditSpec.
func (in *PolicyAuditSpec) DeepCopy() *PolicyAuditSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyAuditSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyKeyReleaseSpec) DeepCopyInto(out *PolicyKeyReleaseSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyKeyReleaseSpec.
func (in *PolicyKeyReleaseSpec) DeepCopy() *PolicyKeyReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyKeyReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawAttestationReport) DeepCopyInto(out *RawAttestationReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawAttestationReport.
func (in *RawAttestationReport) DeepCopy() *RawAttestationReport {
	if in == nil {
		return nil
	}
	out := new(RawAttestationReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RawAttestationReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawAttestationReportList) DeepCopyInto(out *RawAttestationReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RawAttestationReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawAttestationReportList.
func (in *RawAttestationReportList) DeepCopy() *RawAttestationReportList {
	if in == nil {
		return nil
	}
	out := new(RawAttestationReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RawAttestationReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawAttestationReportSpec) DeepCopyInto(out *RawAttestationReportSpec) {
	*out = *in
	in.CollectedAt.DeepCopyInto(&out.CollectedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawAttestationReportSpec.
func (in *RawAttestationReportSpec) DeepCopy() *RawAttestationReportSpec {
	if in == nil {
		return nil
	}
	out := new(RawAttestationReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawAttestationReportStatus) DeepCopyInto(out *RawAttestationReportStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawAttestationReportStatus.
func (in *RawAttestationReportStatus) DeepCopy() *RawAttestationReportStatus {
	if in == nil {
		return nil
	}
	out := new(RawAttestationReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeExpectation) DeepCopyInto(out *RuntimeExpectation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeExpectation.
func (in *RuntimeExpectation) DeepCopy() *RuntimeExpectation {
	if in == nil {
		return nil
	}
	out := new(RuntimeExpectation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadTarget) DeepCopyInto(out *WorkloadTarget) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadTarget.
func (in *WorkloadTarget) DeepCopy() *WorkloadTarget {
	if in == nil {
		return nil
	}
	out := new(WorkloadTarget)
	in.DeepCopyInto(out)
	return out
}
